'use strict';
const $=s=>document.querySelector(s); const canvas=$('#game'),ctx=canvas.getContext('2d');
const menu=$('#menu'),hud=$('#hud'),gameOver=$('#gameOver'),modal=$('#modal'),modalContent=$('#modalContent');
const scoreEl=$('#score'),levelEl=$('#level'),coinsEl=$('#coins'),multiEl=$('#multi'),nameInput=$('#playerName'),statusEl=$('#connectionStatus');
let W=0,H=0,DPR=1,state='menu',last=0,score=0,level=1,runCoins=0,totalCoins=Number(localStorage.getItem('cb_coins')||300),lives=3;
let obstacles=[],pickups=[],particles=[],stars=[],spawnO=0,spawnP=0,spawnMeteor=0,shake=0,flash=0,power={type:'',time:0},multiplier=1,multiTime=0;
let selectedSkin=localStorage.getItem('cb_skin')||'neon'; let owned=JSON.parse(localStorage.getItem('cb_owned')||'["neon"]');
let playerName=localStorage.getItem('cb_name')||''; nameInput.value=playerName;
let missions=JSON.parse(localStorage.getItem('cb_missions')||'{"coins":25,"meteors":5,"dodged":50}');
const ball={x:0,y:0,targetX:0,targetY:0,r:22,trail:[]};
const skins=[
 {id:'neon',name:'Neón azul',price:0,c1:'#ffffff',c2:'#22d3ee',c3:'#4f46e5'},
 {id:'fire',name:'Fuego',price:180,c1:'#fff7ad',c2:'#fb923c',c3:'#b91c1c'},
 {id:'gold',name:'Oro',price:320,c1:'#fffbd1',c2:'#facc15',c3:'#a16207'},
 {id:'forest',name:'Bosque',price:230,c1:'#ecfccb',c2:'#22c55e',c3:'#14532d'},
 {id:'galaxy',name:'Galaxia',price:500,c1:'#f5d0fe',c2:'#a855f7',c3:'#312e81'},
 {id:'football',name:'Balón fútbol',price:420,c1:'#ffffff',c2:'#d1d5db',c3:'#111827'}
];
const cfg=window.CRAZY_BALL_CONFIG||{}; let supabaseClient=null,online=false,channel=null;
try{if(cfg.supabaseUrl&&cfg.supabaseAnonKey&&window.supabase){supabaseClient=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);online=true;statusEl.textContent='Online conectado';}}catch(e){console.warn(e)}
const bc='BroadcastChannel' in window?new BroadcastChannel('crazy-ball-online'):null;
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);if(state!=='play'){ball.x=ball.targetX=W/2;ball.y=ball.targetY=H*.72}if(!stars.length)for(let i=0;i<80;i++)stars.push({x:Math.random()*W,y:Math.random()*H,s:Math.random()*2+.3,v:Math.random()*.6+.15})}
addEventListener('resize',resize,{passive:true});resize();
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function rnd(a,b){return Math.random()*(b-a)+a} function choice(a){return a[Math.floor(Math.random()*a.length)]} function hit(a,b,extra=0){return Math.hypot(a.x-b.x,a.y-b.y)<a.r+b.r+extra}
function safeName(){return (nameInput.value.trim()||'Jugador').replace(/[<>]/g,'').slice(0,18)}
function saveProfile(){playerName=safeName();localStorage.setItem('cb_name',playerName)}
function start(){saveProfile();state='play';menu.classList.add('hidden');gameOver.classList.add('hidden');modal.classList.add('hidden');hud.classList.remove('hidden');score=0;level=1;runCoins=0;lives=3;obstacles=[];pickups=[];particles=[];spawnO=0;spawnP=0;spawnMeteor=90;power={type:'',time:0};multiplier=1;multiTime=0;ball.r=clamp(W*.055,19,27);ball.x=ball.targetX=W/2;ball.y=ball.targetY=H*.76;ball.trail=[];last=performance.now();updateHud()}
function end(){state='over';hud.classList.add('hidden');gameOver.classList.remove('hidden');const final=Math.floor(score);$('#finalScore').textContent=`${final} puntos · nivel ${level} · ${runCoins} monedas`;$('#rankMessage').textContent='Puntuación guardada en el ranking.';totalCoins+=runCoins;localStorage.setItem('cb_coins',totalCoins);submitScore(final,level)}
function setTarget(x,y){if(state!=='play')return;const dx=x-ball.x,dy=y-ball.y,dist=Math.hypot(dx,dy),max=95;if(dist>max){x=ball.x+dx/dist*max;y=ball.y+dy/dist*max}ball.targetX=clamp(x,ball.r,W-ball.r);ball.targetY=clamp(y,105,H-ball.r-10)}
canvas.addEventListener('pointerdown',e=>{setTarget(e.clientX,e.clientY);canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(e.buttons||e.pointerType==='touch')setTarget(e.clientX,e.clientY)});canvas.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});
function spawnObstacle(){const type=choice(['rock','spike','crate','meteor','satellite','mine','laser','portal','comet']);const r=rnd(19,35)+Math.min(level*.35,8);obstacles.push({x:rnd(r,W-r),y:-55,r,vy:rnd(2.3,3.9)+level*.19,type,rot:rnd(0,7),spin:rnd(-.05,.05),phase:rnd(0,7),passed:false})}
function spawnPickup(){const roll=Math.random();let type=roll<.68?'coin':roll<.77?'shield':roll<.85?'magnet':roll<.93?'gold':'multi';pickups.push({x:rnd(25,W-25),y:-35,r:type==='coin'?11:17,vy:rnd(2.2,3.3)+level*.08,type,rot:0,value:type==='multi'?choice([2,2,3,3,5,5,10,20]):1})}
function spawnRandomMeteor(){pickups.push({x:rnd(30,W-30),y:-40,r:20,vy:rnd(2.5,4.2)+level*.1,type:'multi',rot:rnd(0,7),value:choice([2,2,2,3,3,5,5,10,20]),meteor:true})}
function burst(x,y,color,n=18,power=4){for(let i=0;i<n;i++){const a=rnd(0,Math.PI*2),s=rnd(1,power);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rnd(20,48),max:48,r:rnd(2,5),color})}}
function toast(txt){const t=$('#toast');t.textContent=txt;t.classList.add('show');clearTimeout(toast._id);toast._id=setTimeout(()=>t.classList.remove('show'),900)}
function activate(type,value=1){if(type==='multi'){multiplier=value;multiTime=420;toast(`METEORITO x${value}`)}else{power.type=type;power.time=type==='shield'?600:type==='gold'?480:type==='magnet'?600:420;toast(type==='shield'?'ESCUDO':type==='gold'?'SÚPER BOLA':type==='magnet'?'IMÁN':'VENTAJA')}flash=1;burst(ball.x,ball.y,type==='gold'?'#facc15':'#67e8f9',30,7)}
function updateHud(){scoreEl.textContent=Math.floor(score);levelEl.textContent=level;coinsEl.textContent=runCoins;multiEl.textContent='x'+multiplier}
function update(dt){if(state!=='play')return;const f=Math.min(2,dt/16.67);score+=.12*f*multiplier;const oldLevel=level;level=1+Math.floor(score/250);if(level!==oldLevel)toast(`NIVEL ${level}`);ball.x+=(ball.targetX-ball.x)*Math.min(.28*f,1);ball.y+=(ball.targetY-ball.y)*Math.min(.28*f,1);ball.trail.push({x:ball.x,y:ball.y});if(ball.trail.length>12)ball.trail.shift();spawnO-=f;spawnP-=f;spawnMeteor-=f;if(spawnO<=0){spawnObstacle();spawnO=Math.max(20,58-level*2)+rnd(0,18)}if(spawnP<=0){spawnPickup();spawnP=rnd(27,48)}if(spawnMeteor<=0){spawnRandomMeteor();spawnMeteor=rnd(190,340)}
 if(power.time>0){power.time-=f;if(power.time<=0)power={type:'',time:0}}if(multiTime>0){multiTime-=f;if(multiTime<=0){multiplier=1;toast('x1')}}
 for(const o of obstacles){o.y+=o.vy*f;o.rot+=o.spin*f;o.phase+=.04*f;if(o.type==='satellite')o.x+=Math.sin(o.phase)*1.2*f;if(o.type==='laser')o.x+=Math.sin(o.phase)*2.2*f;if(o.y>H+60){o.dead=true;if(!o.passed){o.passed=true;missions.dodged=Math.max(0,missions.dodged-1)}}if(hit(ball,o,-3)){if(power.type==='shield'||power.type==='gold'){o.dead=true;burst(o.x,o.y,'#fff',22,6);shake=7;score+=20*multiplier}else{lives--;o.dead=true;shake=12;flash=.7;burst(ball.x,ball.y,'#fb7185',30,7);if(lives<=0){saveMissions();end();return}}}}
 for(const p of pickups){if(power.type==='magnet'&&p.type==='coin'){const dx=ball.x-p.x,dy=ball.y-p.y,d=Math.max(1,Math.hypot(dx,dy));if(d<190){p.x+=dx/d*7*f;p.y+=dy/d*7*f}}p.y+=p.vy*f;p.rot+=.05*f;if(p.y>H+45)p.dead=true;if(hit(ball,p,2)){p.dead=true;if(p.type==='coin'){runCoins++;score+=12*multiplier;missions.coins=Math.max(0,missions.coins-1);toast('+ MONEDA')}else if(p.type==='multi'){activate('multi',p.value);score+=25*p.value;missions.meteors=Math.max(0,missions.meteors-1)}else activate(p.type);burst(p.x,p.y,p.type==='coin'?'#fde047':'#86efac',20,5)}}
 obstacles=obstacles.filter(o=>!o.dead);pickups=pickups.filter(p=>!p.dead);for(const p of particles){p.x+=p.vx*f;p.y+=p.vy*f;p.vy+=.08*f;p.life-=f}particles=particles.filter(p=>p.life>0);shake*=.86;flash*=.88;updateHud();saveMissions(false)}
function saveMissions(force=true){if(force||Math.random()<.02)localStorage.setItem('cb_missions',JSON.stringify(missions))}
function circleGradient(x,y,r,skin){const g=ctx.createRadialGradient(x-r*.35,y-r*.45,2,x,y,r);g.addColorStop(0,skin.c1);g.addColorStop(.38,skin.c2);g.addColorStop(1,skin.c3);return g}
function drawObstacle(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.rot);ctx.shadowColor='#ff4b5f';ctx.shadowBlur=10;ctx.strokeStyle='#fecaca';ctx.lineWidth=2;if(o.type==='spike'){ctx.fillStyle='#ef4444';ctx.beginPath();for(let i=0;i<12;i++){const a=i*Math.PI/6,rr=i%2?o.r*.48:o.r;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.stroke()}else if(o.type==='satellite'){ctx.fillStyle='#cbd5e1';ctx.fillRect(-o.r*.45,-o.r*.3,o.r*.9,o.r*.6);ctx.fillStyle='#38bdf8';ctx.fillRect(-o.r*1.15,-o.r*.18,o.r*.62,o.r*.36);ctx.fillRect(o.r*.53,-o.r*.18,o.r*.62,o.r*.36)}else if(o.type==='mine'){ctx.fillStyle='#111827';ctx.beginPath();ctx.arc(0,0,o.r*.7,0,7);ctx.fill();ctx.strokeStyle='#ff4b5f';ctx.lineWidth=4;for(let i=0;i<8;i++){const a=i/8*Math.PI*2;ctx.beginPath();ctx.moveTo(Math.cos(a)*o.r*.55,Math.sin(a)*o.r*.55);ctx.lineTo(Math.cos(a)*o.r,Math.sin(a)*o.r);ctx.stroke()}}else if(o.type==='laser'){ctx.fillStyle='#ff284a';ctx.fillRect(-o.r*.2,-o.r,o.r*.4,o.r*2);ctx.fillStyle='#fff';ctx.fillRect(-o.r*.06,-o.r,o.r*.12,o.r*2)}else if(o.type==='portal'){ctx.strokeStyle='#ff4b5f';ctx.lineWidth=6;ctx.beginPath();ctx.ellipse(0,0,o.r*.8,o.r*.45,0,0,7);ctx.stroke();ctx.strokeStyle='#ffd84d';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,o.r*.45,o.r*.25,0,0,7);ctx.stroke()}else if(o.type==='comet'){ctx.fillStyle='#fb7185';ctx.beginPath();ctx.moveTo(-o.r,0);ctx.quadraticCurveTo(0,-o.r*.75,o.r,0);ctx.quadraticCurveTo(0,o.r*.75,-o.r,0);ctx.fill()}else{ctx.fillStyle=o.type==='meteor'?'#7c2d12':o.type==='crate'?'#92400e':'#475569';ctx.beginPath();ctx.roundRect(-o.r,-o.r,o.r*2,o.r*2,8);ctx.fill();ctx.stroke()}ctx.restore()}
function drawPickup(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot);if(p.type==='multi'&&p.meteor){ctx.shadowColor='#b66cff';ctx.shadowBlur=16;ctx.fillStyle=p.value>=10?'#ffd84d':p.value>=5?'#b66cff':'#8b5e3c';ctx.beginPath();ctx.moveTo(-18,-6);ctx.lineTo(-8,-18);ctx.lineTo(12,-14);ctx.lineTo(20,2);ctx.lineTo(8,18);ctx.lineTo(-15,13);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.font='900 11px Arial';ctx.textAlign='center';ctx.fillText('x'+p.value,1,4)}else{const map={coin:['#facc15','€'],shield:['#22d3ee','🛡'],magnet:['#ef4444','🧲'],gold:['#fde047','★'],multi:['#c084fc','x'+p.value]};ctx.fillStyle=map[p.type][0];ctx.beginPath();ctx.arc(0,0,p.r,0,7);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#111827';ctx.font=`bold ${p.type==='multi'?11:14}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(map[p.type][1],0,1)}ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#172d5b');g.addColorStop(.55,'#0a1230');g.addColorStop(1,'#03040c');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(const s of stars){s.y+=s.v;if(s.y>H){s.y=0;s.x=Math.random()*W}ctx.globalAlpha=.38;ctx.fillStyle='#fff';ctx.fillRect(s.x,s.y,s.s,s.s)}ctx.globalAlpha=1;ctx.save();ctx.translate(rnd(-shake,shake),rnd(-shake,shake));for(const o of obstacles)drawObstacle(o);for(const p of pickups)drawPickup(p);const skin=skins.find(s=>s.id===selectedSkin)||skins[0];for(let i=0;i<ball.trail.length;i++){const tr=ball.trail[i];ctx.globalAlpha=(i/ball.trail.length)*.28;ctx.fillStyle=skin.c2;ctx.beginPath();ctx.arc(tr.x,tr.y,ball.r*(i/ball.trail.length),0,7);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle=circleGradient(ball.x,ball.y,ball.r,skin);ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,7);ctx.fill();ctx.strokeStyle=power.type==='shield'?'#67e8f9':power.type==='gold'?'#fef08a':'#fff';ctx.lineWidth=power.type?6:3;ctx.stroke();if(power.type==='shield'){ctx.strokeStyle='rgba(103,232,249,.55)';ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r+11,0,7);ctx.stroke()}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()}ctx.globalAlpha=1;ctx.restore();if(state==='play'){ctx.fillStyle='white';ctx.font='bold 15px Arial';ctx.textAlign='center';ctx.fillText(`Vidas: ${'❤'.repeat(lives)}`,W/2,94);if(power.type){ctx.fillStyle='#fde68a';ctx.fillText(`${power.type.toUpperCase()} ${Math.ceil(power.time/60)}s`,W/2,H-22)}}if(flash>.02){ctx.fillStyle=`rgba(255,255,255,${flash*.35})`;ctx.fillRect(0,0,W,H)}}
function loop(now){const dt=now-last||16;last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
async function submitScore(points,lvl){const row={player_name:playerName||'Jugador',score:points,level:lvl};let local=JSON.parse(localStorage.getItem('cb_scores')||'[]');local.push({...row,created_at:new Date().toISOString()});local=local.sort((a,b)=>b.score-a.score).slice(0,100);localStorage.setItem('cb_scores',JSON.stringify(local));bc?.postMessage({type:'score',row});if(online){try{await supabaseClient.from('scores').insert(row)}catch(e){console.warn(e)}}}
async function getScores(){if(online){try{const {data,error}=await supabaseClient.from('scores').select('*').order('score',{ascending:false}).limit(50);if(!error&&data)return data}catch(e){console.warn(e)}}return JSON.parse(localStorage.getItem('cb_scores')||'[]').sort((a,b)=>b.score-a.score).slice(0,50)}
async function openRanking(){const rows=await getScores();modalContent.innerHTML=`<h2>RANKING GLOBAL</h2><div>${rows.length?rows.map((r,i)=>`<div class="rank-row"><span class="rank-pos">${i+1}</span><span class="rank-name">${escapeHtml(r.player_name)}</span><span class="rank-score">${r.score}</span></div>`).join(''):'<p>Aún no hay puntuaciones.</p>'}</div>`;openModal()}
function getLocalMessages(){return JSON.parse(localStorage.getItem('cb_chat')||'[]').slice(-80)} function saveLocalMessage(m){const a=getLocalMessages();a.push(m);localStorage.setItem('cb_chat',JSON.stringify(a.slice(-80)));bc?.postMessage({type:'chat',row:m})}
async function getMessages(){if(online){try{const {data,error}=await supabaseClient.from('messages').select('*').order('created_at',{ascending:true}).limit(80);if(!error&&data)return data}catch(e){console.warn(e)}}return getLocalMessages()}
async function openChat(){saveProfile();const msgs=await getMessages();modalContent.innerHTML=`<h2>CHAT ONLINE</h2><div id="chatLog" class="chat-log"></div><div class="chat-compose"><input id="chatInput" class="input" maxlength="140" placeholder="Escribe un mensaje"><button id="sendChat" class="btn primary">Enviar</button></div>`;renderMessages(msgs);$('#sendChat').onclick=sendChat;$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendChat()});openModal();subscribeChat()}
function renderMessages(msgs){const log=$('#chatLog');if(!log)return;log.innerHTML=msgs.map(m=>`<div class="chat-row"><small>${escapeHtml(m.player_name)}</small><div>${escapeHtml(m.message)}</div></div>`).join('');log.scrollTop=log.scrollHeight}
async function sendChat(){const input=$('#chatInput'),message=(input?.value||'').trim().slice(0,140);if(!message)return;const row={player_name:playerName||'Jugador',message,created_at:new Date().toISOString()};saveLocalMessage(row);if(online){try{await supabaseClient.from('messages').insert({player_name:row.player_name,message:row.message})}catch(e){console.warn(e)}}input.value='';renderMessages(await getMessages())}
function subscribeChat(){if(!online||channel)return;channel=supabaseClient.channel('crazy-ball-chat').on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},async()=>renderMessages(await getMessages())).subscribe()}
bc?.addEventListener('message',async e=>{if(e.data?.type==='chat'&&$('#chatLog'))renderMessages(await getMessages());if(e.data?.type==='score'&&modalContent.textContent.includes('RANKING'))openRanking()});
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))} function openModal(){modal.classList.remove('hidden')} function closeModal(){modal.classList.add('hidden')}
function openSkins(){modalContent.innerHTML=`<h2>SKINS</h2><p>Monedas disponibles: <b>${totalCoins}</b></p><div class="skin-grid">${skins.map(s=>{const isOwned=owned.includes(s.id),sel=selectedSkin===s.id;return `<div class="skin-card"><div class="skin-ball" style="background:radial-gradient(circle at 30% 25%,${s.c1},${s.c2} 40%,${s.c3})"></div><b>${s.name}</b><button class="btn ${sel?'primary':'secondary'}" data-skin="${s.id}">${sel?'EQUIPADA':isOwned?'EQUIPAR':s.price+' monedas'}</button></div>`}).join('')}</div>`;modalContent.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>buyOrSelect(b.dataset.skin));openModal()}
function buyOrSelect(id){const s=skins.find(x=>x.id===id);if(!owned.includes(id)){if(totalCoins<s.price){alert('No tienes suficientes monedas.');return}totalCoins-=s.price;owned.push(id);localStorage.setItem('cb_coins',totalCoins);localStorage.setItem('cb_owned',JSON.stringify(owned))}selectedSkin=id;localStorage.setItem('cb_skin',id);openSkins()}
function openMissions(){saveMissions();modalContent.innerHTML=`<h2>MISIONES</h2><div class="mission-row">🪙 Recoge monedas <b>${missions.coins>0?missions.coins:'COMPLETADA'}</b></div><div class="mission-row">☄️ Consigue meteoritos <b>${missions.meteors>0?missions.meteors:'COMPLETADA'}</b></div><div class="mission-row">🚀 Esquiva objetos <b>${missions.dodged>0?missions.dodged:'COMPLETADA'}</b></div><p class="mission-note">El progreso se guarda automáticamente.</p>`;openModal()}
function openHow(){modalContent.innerHTML='<h2>CÓMO JUGAR</h2><p>Arrastra el dedo cerca de la bola para moverla sin que se coloque directamente bajo tu pulsación. Recoge monedas, ventajas y meteoritos con multiplicadores aleatorios. Evita rocas, pinchos, satélites, minas, láseres, portales y cometas.</p>';openModal()}
$('#playBtn').onclick=start;$('#retryBtn').onclick=start;$('#homeBtn').onclick=()=>{state='menu';gameOver.classList.add('hidden');menu.classList.remove('hidden')};$('#rankingBtn').onclick=openRanking;$('#chatBtn').onclick=openChat;$('#skinsBtn').onclick=openSkins;$('#missionsBtn').onclick=openMissions;$('#howBtn').onclick=openHow;$('#closeModal').onclick=closeModal;$('#pauseBtn').onclick=()=>{if(state==='play'){state='pause';modalContent.innerHTML='<h2>PAUSA</h2><button id="resume" class="btn primary">CONTINUAR</button><button id="quit" class="btn secondary">SALIR AL MENÚ</button>';openModal();$('#resume').onclick=()=>{state='play';closeModal()};$('#quit').onclick=()=>{state='menu';hud.classList.add('hidden');closeModal();menu.classList.remove('hidden')}}};
