'use strict';
const $=s=>document.querySelector(s); const canvas=$('#game'),ctx=canvas.getContext('2d');
const menu=$('#menu'),hud=$('#hud'),gameOver=$('#gameOver'),modal=$('#modal'),modalContent=$('#modalContent');
const scoreEl=$('#score'),levelEl=$('#level'),prestigeEl=$('#prestige'),coinsEl=$('#coins'),multiEl=$('#multi'),nameInput=$('#playerName'),statusEl=$('#connectionStatus');
let W=0,H=0,DPR=1,state='menu',last=0,score=0,level=1,runCoins=0,totalCoins=Number(localStorage.getItem('cb_coins')||300),lives=3;
let prestige=Number(localStorage.getItem('cb_prestige')||0), highestLevel=Number(localStorage.getItem('cb_highest_level')||1), rewardedPrestige=Number(localStorage.getItem('cb_rewarded_prestige')||0);
let gameMode=localStorage.getItem('cb_mode')||'classic';
let inventory=JSON.parse(localStorage.getItem('cb_inventory')||'{"shield":1,"magnet":1,"gold":1,"slow":0,"double":0}');
let obstacles=[],pickups=[],particles=[],stars=[],spawnO=0,spawnP=0,spawnMeteor=0,shake=0,flash=0,power={type:'',time:0},multiplier=1,multiTime=0;
let selectedSkin=localStorage.getItem('cb_skin')||'neon'; let owned=JSON.parse(localStorage.getItem('cb_owned')||'["neon"]');
let playerName=localStorage.getItem('cb_name')||''; nameInput.value=playerName;
let missions=JSON.parse(localStorage.getItem('cb_missions')||'{"coins":25,"meteors":5,"dodged":50}');
const ball={x:0,y:0,targetX:0,targetY:0,r:22,trail:[]};
const skins=[
 {id:'neon',name:'Neón azul',cat:'Originales',price:0,c1:'#ffffff',c2:'#22d3ee',c3:'#4f46e5'},
 {id:'fire',name:'Fuego extremo',cat:'Originales',price:180,c1:'#fff7ad',c2:'#fb923c',c3:'#b91c1c'},
 {id:'gold',name:'Oro campeón',cat:'Originales',price:320,c1:'#fffbd1',c2:'#facc15',c3:'#a16207'},
 {id:'forest',name:'Bosque',cat:'Originales',price:230,c1:'#ecfccb',c2:'#22c55e',c3:'#14532d'},
 {id:'galaxy',name:'Galaxia',cat:'Originales',price:500,c1:'#f5d0fe',c2:'#a855f7',c3:'#312e81'},
 {id:'ice',name:'Hielo',cat:'Originales',price:260,c1:'#ffffff',c2:'#7dd3fc',c3:'#075985'},
 {id:'lava',name:'Lava',cat:'Originales',price:420,c1:'#fff7ed',c2:'#f97316',c3:'#7f1d1d'},
 {id:'shadow',name:'Sombra',cat:'Originales',price:550,c1:'#94a3b8',c2:'#334155',c3:'#020617'},
 {id:'football',name:'Balón clásico',cat:'Fútbol',price:420,c1:'#ffffff',c2:'#d1d5db',c3:'#111827'},
 {id:'redclub',name:'Club rojo',cat:'Fútbol',price:520,c1:'#ffffff',c2:'#ef4444',c3:'#7f1d1d'},
 {id:'blueclub',name:'Club azul',cat:'Fútbol',price:520,c1:'#ffffff',c2:'#3b82f6',c3:'#172554'},
 {id:'greenclub',name:'Club verde',cat:'Fútbol',price:520,c1:'#f0fdf4',c2:'#22c55e',c3:'#14532d'},
 {id:'yellowclub',name:'Club amarillo',cat:'Fútbol',price:520,c1:'#fff',c2:'#facc15',c3:'#854d0e'},
 {id:'royalclub',name:'Club real',cat:'Fútbol',price:700,c1:'#fff',c2:'#e5e7eb',c3:'#7c3aed'},
 {id:'nightkeeper',name:'Guardián nocturno',cat:'Héroes',price:780,c1:'#cbd5e1',c2:'#1e3a8a',c3:'#020617'},
 {id:'solarhero',name:'Héroe solar',cat:'Héroes',price:780,c1:'#fff7ad',c2:'#ef4444',c3:'#1d4ed8'},
 {id:'webhero',name:'Héroe arácnido',cat:'Héroes',price:850,c1:'#ffffff',c2:'#dc2626',c3:'#1e3a8a'},
 {id:'ironhero',name:'Armadura carmesí',cat:'Héroes',price:900,c1:'#fde68a',c2:'#dc2626',c3:'#7f1d1d'},
 {id:'stormhero',name:'Guardián del trueno',cat:'Héroes',price:950,c1:'#ffffff',c2:'#60a5fa',c3:'#312e81'},
 {id:'sparkmouse',name:'Ratón eléctrico',cat:'Criaturas',price:760,c1:'#fff7ad',c2:'#facc15',c3:'#92400e'},
 {id:'firelizard',name:'Lagarto de fuego',cat:'Criaturas',price:760,c1:'#ffedd5',c2:'#f97316',c3:'#9a3412'},
 {id:'waterbeast',name:'Bestia acuática',cat:'Criaturas',price:760,c1:'#e0f2fe',c2:'#0ea5e9',c3:'#164e63'},
 {id:'leafbeast',name:'Criatura hoja',cat:'Criaturas',price:760,c1:'#ecfccb',c2:'#65a30d',c3:'#365314'},
 {id:'psychic',name:'Criatura psíquica',cat:'Criaturas',price:980,c1:'#fae8ff',c2:'#d946ef',c3:'#581c87'},
 {id:'dragon',name:'Dragón celeste',cat:'Criaturas',price:1200,c1:'#e0f2fe',c2:'#38bdf8',c3:'#1e3a8a'}
];
const cfg=window.CRAZY_BALL_CONFIG||{}; let supabaseClient=null,online=false,channel=null;
try{if(cfg.supabaseUrl&&cfg.supabaseAnonKey&&window.supabase){supabaseClient=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);online=true;statusEl.textContent='Online conectado';}}catch(e){console.warn(e)}
const bc='BroadcastChannel' in window?new BroadcastChannel('crazy-ball-online'):null;
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);if(state!=='play'){ball.x=ball.targetX=W/2;ball.y=ball.targetY=H*.72}if(!stars.length)for(let i=0;i<80;i++)stars.push({x:Math.random()*W,y:Math.random()*H,s:Math.random()*2+.3,v:Math.random()*.6+.15})}
addEventListener('resize',resize,{passive:true});resize();
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function rnd(a,b){return Math.random()*(b-a)+a} function choice(a){return a[Math.floor(Math.random()*a.length)]} function hit(a,b,extra=0){return Math.hypot(a.x-b.x,a.y-b.y)<a.r+b.r+extra}
function safeName(){return (nameInput.value.trim()||'Jugador').replace(/[<>]/g,'').slice(0,18)}
function saveProfile(){playerName=safeName();localStorage.setItem('cb_name',playerName)}
function start(){saveProfile();state='play';menu.classList.add('hidden');gameOver.classList.add('hidden');modal.classList.add('hidden');hud.classList.remove('hidden');score=0;level=1;runCoins=0;lives=gameMode==='survival'?1:3;obstacles=[];pickups=[];particles=[];spawnO=0;spawnP=0;spawnMeteor=90;power={type:'',time:0};multiplier=1;multiTime=0;applyStartingPower();ball.r=clamp(W*.055,19,27);ball.x=ball.targetX=W/2;ball.y=ball.targetY=H*.76;ball.trail=[];last=performance.now();updateHud()}
function end(){state='over';hud.classList.add('hidden');gameOver.classList.remove('hidden');const final=Math.floor(score);$('#finalScore').textContent=`${final} puntos · nivel ${level} · ${runCoins} monedas`;$('#rankMessage').textContent='Puntuación guardada en el ranking.';highestLevel=Math.max(highestLevel,level);localStorage.setItem('cb_highest_level',highestLevel);const newPrestige=Math.floor(highestLevel/10);if(newPrestige>rewardedPrestige){const gained=(newPrestige-rewardedPrestige)*1000;totalCoins+=gained;rewardedPrestige=newPrestige;prestige=newPrestige;localStorage.setItem('cb_rewarded_prestige',rewardedPrestige);localStorage.setItem('cb_prestige',prestige);$('#rankMessage').textContent=`¡Prestigio ${prestige}! Premio: ${gained} monedas.`}totalCoins+=runCoins;localStorage.setItem('cb_coins',totalCoins);submitScore(final,level)}
function setTarget(x,y){if(state!=='play')return;const dx=x-ball.x,dy=y-ball.y,dist=Math.hypot(dx,dy),max=95;if(dist>max){x=ball.x+dx/dist*max;y=ball.y+dy/dist*max}ball.targetX=clamp(x,ball.r,W-ball.r);ball.targetY=clamp(y,105,H-ball.r-10)}
canvas.addEventListener('pointerdown',e=>{setTarget(e.clientX,e.clientY);canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(e.buttons||e.pointerType==='touch')setTarget(e.clientX,e.clientY)});canvas.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});
function spawnObstacle(){const type=choice(['rock','spike','crate','meteor','satellite','mine','laser','portal','comet']);const r=rnd(19,35)+Math.min(level*.35,10);const modeSpeed=gameMode==='survival'?1.35:gameMode==='meteor'?1.18:1;obstacles.push({x:rnd(r,W-r),y:-55,r,vy:(rnd(2.3,3.9)+level*.23)*modeSpeed,type,rot:rnd(0,7),spin:rnd(-.05,.05),phase:rnd(0,7),passed:false})}
function spawnPickup(){const roll=Math.random();let type;if(gameMode==='coins')type=roll<.82?'coin':roll<.88?'magnet':roll<.94?'double':'shield';else if(gameMode==='meteor')type=roll<.42?'coin':roll<.76?'multi':roll<.84?'shield':roll<.92?'magnet':'gold';else type=roll<.60?'coin':roll<.69?'shield':roll<.78?'magnet':roll<.86?'gold':roll<.93?'slow':roll<.97?'double':'multi';pickups.push({x:rnd(25,W-25),y:-35,r:type==='coin'?11:17,vy:rnd(2.2,3.3)+level*.08,type,rot:0,value:type==='multi'?choice([2,2,3,3,5,5,10,20]):1})}
function spawnRandomMeteor(){pickups.push({x:rnd(30,W-30),y:-40,r:20,vy:rnd(2.5,4.2)+level*.1,type:'multi',rot:rnd(0,7),value:choice([2,2,2,3,3,5,5,10,20]),meteor:true})}
function burst(x,y,color,n=18,power=4){for(let i=0;i<n;i++){const a=rnd(0,Math.PI*2),s=rnd(1,power);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rnd(20,48),max:48,r:rnd(2,5),color})}}
function toast(txt){const t=$('#toast');t.textContent=txt;t.classList.add('show');clearTimeout(toast._id);toast._id=setTimeout(()=>t.classList.remove('show'),900)}
function activate(type,value=1){if(type==='multi'){multiplier=value;multiTime=420;toast(`METEORITO x${value}`)}else{power.type=type;power.time=type==='shield'?600:type==='gold'?480:type==='magnet'?600:type==='slow'?420:type==='double'?480:420;toast(type==='shield'?'ESCUDO':type==='gold'?'SÚPER BOLA':type==='magnet'?'IMÁN':type==='slow'?'TIEMPO LENTO':type==='double'?'MONEDAS x2':'VENTAJA')}flash=1;burst(ball.x,ball.y,type==='gold'?'#facc15':'#67e8f9',30,7)}
function updateHud(){scoreEl.textContent=Math.floor(score);levelEl.textContent=level;prestigeEl.textContent=prestige;coinsEl.textContent=runCoins;multiEl.textContent='x'+multiplier}
function update(dt){if(state!=='play')return;const f=Math.min(2,dt/16.67);const timeFactor=power.type==='slow'?.62:1;score+=.12*f*multiplier*(gameMode==='survival'?1.35:1);const oldLevel=level;level=1+Math.floor(score/220);if(level!==oldLevel)toast(`NIVEL ${level}`);ball.x+=(ball.targetX-ball.x)*Math.min(.28*f,1);ball.y+=(ball.targetY-ball.y)*Math.min(.28*f,1);ball.trail.push({x:ball.x,y:ball.y});if(ball.trail.length>12)ball.trail.shift();spawnO-=f;spawnP-=f;spawnMeteor-=f;if(spawnO<=0){spawnObstacle();spawnO=(Math.max(12,58-level*2.6)+rnd(0,15))*(gameMode==='survival'?.72:gameMode==='meteor'?.82:1)}if(spawnP<=0){spawnPickup();spawnP=rnd(gameMode==='coins'?13:24,gameMode==='coins'?26:45)}if(spawnMeteor<=0){spawnRandomMeteor();spawnMeteor=rnd(190,340)}
 if(power.time>0){power.time-=f;if(power.time<=0)power={type:'',time:0}}if(multiTime>0){multiTime-=f;if(multiTime<=0){multiplier=1;toast('x1')}}
 for(const o of obstacles){o.y+=o.vy*f*timeFactor;o.rot+=o.spin*f;o.phase+=.04*f;if(o.type==='satellite')o.x+=Math.sin(o.phase)*1.2*f;if(o.type==='laser')o.x+=Math.sin(o.phase)*2.2*f;if(o.y>H+60){o.dead=true;if(!o.passed){o.passed=true;missions.dodged=Math.max(0,missions.dodged-1)}}if(hit(ball,o,-3)){if(power.type==='shield'||power.type==='gold'){o.dead=true;burst(o.x,o.y,'#fff',22,6);shake=7;score+=20*multiplier}else{lives--;o.dead=true;shake=12;flash=.7;burst(ball.x,ball.y,'#fb7185',30,7);if(lives<=0){saveMissions();end();return}}}}
 for(const p of pickups){if(power.type==='magnet'&&p.type==='coin'){const dx=ball.x-p.x,dy=ball.y-p.y,d=Math.max(1,Math.hypot(dx,dy));if(d<190){p.x+=dx/d*7*f;p.y+=dy/d*7*f}}p.y+=p.vy*f*timeFactor;p.rot+=.05*f;if(p.y>H+45)p.dead=true;if(hit(ball,p,2)){p.dead=true;if(p.type==='coin'){const coinGain=power.type==='double'?2:1;runCoins+=coinGain;score+=12*multiplier*coinGain;missions.coins=Math.max(0,missions.coins-1);toast('+ MONEDA')}else if(p.type==='multi'){activate('multi',p.value);score+=25*p.value;missions.meteors=Math.max(0,missions.meteors-1)}else activate(p.type);burst(p.x,p.y,p.type==='coin'?'#fde047':'#86efac',20,5)}}
 obstacles=obstacles.filter(o=>!o.dead);pickups=pickups.filter(p=>!p.dead);for(const p of particles){p.x+=p.vx*f;p.y+=p.vy*f*timeFactor;p.vy+=.08*f;p.life-=f}particles=particles.filter(p=>p.life>0);shake*=.86;flash*=.88;updateHud();saveMissions(false)}
function saveMissions(force=true){if(force||Math.random()<.02)localStorage.setItem('cb_missions',JSON.stringify(missions))}
function circleGradient(x,y,r,skin){const g=ctx.createRadialGradient(x-r*.35,y-r*.45,2,x,y,r);g.addColorStop(0,skin.c1);g.addColorStop(.38,skin.c2);g.addColorStop(1,skin.c3);return g}
function drawObstacle(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.rot);ctx.shadowColor='#ff4b5f';ctx.shadowBlur=10;ctx.strokeStyle='#fecaca';ctx.lineWidth=2;if(o.type==='spike'){ctx.fillStyle='#ef4444';ctx.beginPath();for(let i=0;i<12;i++){const a=i*Math.PI/6,rr=i%2?o.r*.48:o.r;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.stroke()}else if(o.type==='satellite'){ctx.fillStyle='#cbd5e1';ctx.fillRect(-o.r*.45,-o.r*.3,o.r*.9,o.r*.6);ctx.fillStyle='#38bdf8';ctx.fillRect(-o.r*1.15,-o.r*.18,o.r*.62,o.r*.36);ctx.fillRect(o.r*.53,-o.r*.18,o.r*.62,o.r*.36)}else if(o.type==='mine'){ctx.fillStyle='#111827';ctx.beginPath();ctx.arc(0,0,o.r*.7,0,7);ctx.fill();ctx.strokeStyle='#ff4b5f';ctx.lineWidth=4;for(let i=0;i<8;i++){const a=i/8*Math.PI*2;ctx.beginPath();ctx.moveTo(Math.cos(a)*o.r*.55,Math.sin(a)*o.r*.55);ctx.lineTo(Math.cos(a)*o.r,Math.sin(a)*o.r);ctx.stroke()}}else if(o.type==='laser'){ctx.fillStyle='#ff284a';ctx.fillRect(-o.r*.2,-o.r,o.r*.4,o.r*2);ctx.fillStyle='#fff';ctx.fillRect(-o.r*.06,-o.r,o.r*.12,o.r*2)}else if(o.type==='portal'){ctx.strokeStyle='#ff4b5f';ctx.lineWidth=6;ctx.beginPath();ctx.ellipse(0,0,o.r*.8,o.r*.45,0,0,7);ctx.stroke();ctx.strokeStyle='#ffd84d';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,o.r*.45,o.r*.25,0,0,7);ctx.stroke()}else if(o.type==='comet'){ctx.fillStyle='#fb7185';ctx.beginPath();ctx.moveTo(-o.r,0);ctx.quadraticCurveTo(0,-o.r*.75,o.r,0);ctx.quadraticCurveTo(0,o.r*.75,-o.r,0);ctx.fill()}else{ctx.fillStyle=o.type==='meteor'?'#7c2d12':o.type==='crate'?'#92400e':'#475569';ctx.beginPath();ctx.roundRect(-o.r,-o.r,o.r*2,o.r*2,8);ctx.fill();ctx.stroke()}ctx.restore()}
function drawPickup(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot);if(p.type==='multi'&&p.meteor){ctx.shadowColor='#b66cff';ctx.shadowBlur=16;ctx.fillStyle=p.value>=10?'#ffd84d':p.value>=5?'#b66cff':'#8b5e3c';ctx.beginPath();ctx.moveTo(-18,-6);ctx.lineTo(-8,-18);ctx.lineTo(12,-14);ctx.lineTo(20,2);ctx.lineTo(8,18);ctx.lineTo(-15,13);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.font='900 11px Arial';ctx.textAlign='center';ctx.fillText('x'+p.value,1,4)}else{const map={coin:['#facc15','€'],shield:['#22d3ee','🛡'],magnet:['#ef4444','🧲'],gold:['#fde047','★'],slow:['#a78bfa','⏱'],double:['#34d399','x2'],multi:['#c084fc','x'+p.value]};ctx.fillStyle=map[p.type][0];ctx.beginPath();ctx.arc(0,0,p.r,0,7);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#111827';ctx.font=`bold ${p.type==='multi'?11:14}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(map[p.type][1],0,1)}ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#172d5b');g.addColorStop(.55,'#0a1230');g.addColorStop(1,'#03040c');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);drawFloor();for(const s of stars){s.y+=s.v;if(s.y>H){s.y=0;s.x=Math.random()*W}ctx.globalAlpha=.38;ctx.fillStyle='#fff';ctx.fillRect(s.x,s.y,s.s,s.s)}ctx.globalAlpha=1;ctx.save();ctx.translate(rnd(-shake,shake),rnd(-shake,shake));for(const o of obstacles)drawObstacle(o);for(const p of pickups)drawPickup(p);const skin=skins.find(s=>s.id===selectedSkin)||skins[0];for(let i=0;i<ball.trail.length;i++){const tr=ball.trail[i];ctx.globalAlpha=(i/ball.trail.length)*.28;ctx.fillStyle=skin.c2;ctx.beginPath();ctx.arc(tr.x,tr.y,ball.r*(i/ball.trail.length),0,7);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle=circleGradient(ball.x,ball.y,ball.r,skin);ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,7);ctx.fill();ctx.strokeStyle=power.type==='shield'?'#67e8f9':power.type==='gold'?'#fef08a':'#fff';ctx.lineWidth=power.type?6:3;ctx.stroke();if(power.type==='shield'){ctx.strokeStyle='rgba(103,232,249,.55)';ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r+11,0,7);ctx.stroke()}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()}ctx.globalAlpha=1;ctx.restore();if(state==='play'){ctx.fillStyle='white';ctx.font='bold 15px Arial';ctx.textAlign='center';ctx.fillText(`Vidas: ${'❤'.repeat(lives)}`,W/2,94);if(power.type){ctx.fillStyle='#fde68a';ctx.fillText(`${power.type.toUpperCase()} ${Math.ceil(power.time/60)}s`,W/2,H-22)}}if(flash>.02){ctx.fillStyle=`rgba(255,255,255,${flash*.35})`;ctx.fillRect(0,0,W,H)}}

function drawFloor(){const horizon=H*.64;ctx.save();const fg=ctx.createLinearGradient(0,horizon,0,H);fg.addColorStop(0,'rgba(38,55,105,.10)');fg.addColorStop(1,'rgba(2,4,15,.95)');ctx.fillStyle=fg;ctx.fillRect(0,horizon,W,H-horizon);ctx.strokeStyle='rgba(56,189,248,.18)';ctx.lineWidth=1;for(let i=0;i<18;i++){const y=horizon+(H-horizon)*(i/18)**1.7;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(let i=-10;i<=10;i++){ctx.beginPath();ctx.moveTo(W/2+i*18,horizon);ctx.lineTo(W/2+i*85,H);ctx.stroke()}ctx.restore()}
function applyStartingPower(){for(const key of ['shield','magnet','gold','slow','double']){if(inventory[key]>0){inventory[key]--;localStorage.setItem('cb_inventory',JSON.stringify(inventory));activate(key);break}}}
function loop(now){const dt=now-last||16;last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
async function submitScore(points,lvl){const row={player_name:playerName||'Jugador',score:points,level:lvl};let local=JSON.parse(localStorage.getItem('cb_scores')||'[]');local.push({...row,created_at:new Date().toISOString()});local=local.sort((a,b)=>b.score-a.score).slice(0,100);localStorage.setItem('cb_scores',JSON.stringify(local));bc?.postMessage({type:'score',row});if(online){try{await supabaseClient.from('scores').insert(row)}catch(e){console.warn(e)}}}
async function getScores(){if(online){try{const {data,error}=await supabaseClient.from('scores').select('*').order('score',{ascending:false}).limit(50);if(!error&&data)return data}catch(e){console.warn(e)}}return JSON.parse(localStorage.getItem('cb_scores')||'[]').sort((a,b)=>b.score-a.score).slice(0,50)}
async function openRanking(){const rows=await getScores();modalContent.innerHTML=`<h2>RANKING GLOBAL</h2><div>${rows.length?rows.map((r,i)=>`<div class="rank-row"><span class="rank-pos">${i+1}</span><span class="rank-name">${escapeHtml(r.player_name)}</span><span class="rank-score">${r.score}</span></div>`).join(''):'<p>Aún no hay puntuaciones.</p>'}</div>`;openModal()}
function getLocalMessages(){return JSON.parse(localStorage.getItem('cb_chat')||'[]').slice(-80)} function saveLocalMessage(m){const a=getLocalMessages();a.push(m);localStorage.setItem('cb_chat',JSON.stringify(a.slice(-80)));bc?.postMessage({type:'chat',row:m})}
async function getMessages(){if(online){try{const {data,error}=await supabaseClient.from('messages').select('*').order('created_at',{ascending:true}).limit(80);if(!error&&data)return data}catch(e){console.warn(e)}}return getLocalMessages()}
async function openChat(){saveProfile();const msgs=await getMessages();modalContent.innerHTML=`<h2>CHAT ONLINE</h2><div id="chatLog" class="chat-log"></div><div class="chat-compose"><input id="chatInput" class="input" maxlength="140" placeholder="Escribe un mensaje"><button id="sendChat" class="btn primary">Enviar</button></div>`;renderMessages(msgs);$('#sendChat').onclick=sendChat;$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendChat()});openModal();subscribeChat()}
function renderMessages(msgs){const log=$('#chatLog');if(!log)return;log.innerHTML=msgs.map(m=>`<div class="chat-row"><small>${escapeHtml(m.player_name)}</small><div>${escapeHtml(m.message)}</div></div>`).join('');log.scrollTop=log.scrollHeight}
async function sendChat(){const input=$('#chatInput'),message=(input?.value||'').trim().slice(0,140);if(!message)return;const row={player_name:playerName||'Jugador',message,created_at:new Date().toISOString()};saveLocalMessage(row);if(online){try{await supabaseClient.from('messages').insert({player_name:row.player_name,message:row.message})}catch(e){console.warn(e)}}input.value='';renderMessages(await getMessages())}
function subscribeChat(){if(!online||channel)return;channel=supabaseClient.channel('crazy-ball-chat').on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},async()=>renderMessages(await getMessages())).subscribe()}
bc?.addEventListener('message',async e=>{if(e.data?.type==='chat'&&$('#chatLog'))renderMessages(await getMessages());if(e.data?.type==='score'&&modalContent.textContent.includes('RANKING'))openRanking()});
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))} function openModal(){modal.classList.remove('hidden')} function closeModal(){modal.classList.add('hidden')}
function openSkins(){const cats=[...new Set(skins.map(s=>s.cat))];modalContent.innerHTML=`<h2>TIENDA DE SKINS</h2><p>Monedas disponibles: <b>${totalCoins}</b></p>${cats.map(cat=>`<h3>${cat}</h3><div class="skin-grid">${skins.filter(s=>s.cat===cat).map(s=>{const isOwned=owned.includes(s.id),sel=selectedSkin===s.id;return `<div class="skin-card"><div class="skin-ball" style="background:radial-gradient(circle at 30% 25%,${s.c1},${s.c2} 40%,${s.c3})"></div><b>${s.name}</b><small>${s.price?`${s.price} monedas`:'GRATIS'}</small><button class="btn ${sel?'primary':'secondary'}" data-skin="${s.id}">${sel?'EQUIPADA':isOwned?'EQUIPAR':'COMPRAR'}</button></div>`}).join('')}</div>`).join('')}`;modalContent.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>buyOrSelect(b.dataset.skin));openModal()}
function buyOrSelect(id){const s=skins.find(x=>x.id===id);if(!owned.includes(id)){if(totalCoins<s.price){alert('No tienes suficientes monedas.');return}totalCoins-=s.price;owned.push(id);localStorage.setItem('cb_coins',totalCoins);localStorage.setItem('cb_owned',JSON.stringify(owned))}selectedSkin=id;localStorage.setItem('cb_skin',id);openSkins()}
function openMissions(){saveMissions();const allDone=missions.coins<=0&&missions.meteors<=0&&missions.dodged<=0;modalContent.innerHTML=`<h2>MISIONES</h2><div class="mission-row">🪙 Recoge 25 monedas <b>${missions.coins>0?missions.coins:'✓'}</b></div><div class="mission-row">☄️ Consigue 5 meteoritos <b>${missions.meteors>0?missions.meteors:'✓'}</b></div><div class="mission-row">🚀 Esquiva 50 objetos <b>${missions.dodged>0?missions.dodged:'✓'}</b></div>${allDone?'<button id="claimMission" class="btn primary">COBRAR 500 MONEDAS</button>':''}<p class="mission-note">El progreso se guarda automáticamente.</p>`;if(allDone)$('#claimMission').onclick=()=>{totalCoins+=500;localStorage.setItem('cb_coins',totalCoins);missions={coins:25,meteors:5,dodged:50};saveMissions();toast('+500 MONEDAS');openMissions()};openModal()}

function openModes(){const modes=[['classic','Clásico','Equilibrado: monedas, ventajas y obstáculos.'],['coins','Lluvia de monedas','Más monedas y mayor frecuencia de imanes.'],['survival','Supervivencia','Una sola vida, velocidad alta y más puntuación.'],['meteor','Tormenta de meteoritos','Muchos multiplicadores y obstáculos rápidos.']];modalContent.innerHTML=`<h2>MODOS DE JUEGO</h2>${modes.map(m=>`<button class="mode-card ${gameMode===m[0]?'selected':''}" data-mode="${m[0]}"><b>${m[1]}</b><span>${m[2]}</span></button>`).join('')}`;modalContent.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{gameMode=b.dataset.mode;localStorage.setItem('cb_mode',gameMode);openModes()});openModal()}
function openPowers(){const items=[['shield','Escudo inicial',180,'Protege del primer impacto.'],['magnet','Imán inicial',220,'Atrae monedas cercanas.'],['gold','Súper bola inicial',320,'Destruye obstáculos temporalmente.'],['slow','Tiempo lento',260,'Reduce la velocidad del escenario.'],['double','Monedas x2',300,'Duplica las monedas recogidas.']];modalContent.innerHTML=`<h2>VENTAJAS</h2><p>Monedas: <b>${totalCoins}</b></p>${items.map(i=>`<div class="power-shop"><div><b>${i[1]}</b><small>${i[3]}</small></div><button class="btn secondary" data-power="${i[0]}">${i[2]} 🪙 · Tienes ${inventory[i[0]]||0}</button></div>`).join('')}`;modalContent.querySelectorAll('[data-power]').forEach(b=>b.onclick=()=>{const it=items.find(x=>x[0]===b.dataset.power);if(totalCoins<it[2]){alert('No tienes suficientes monedas.');return}totalCoins-=it[2];inventory[it[0]]=(inventory[it[0]]||0)+1;localStorage.setItem('cb_coins',totalCoins);localStorage.setItem('cb_inventory',JSON.stringify(inventory));openPowers()});openModal()}
function openHow(){modalContent.innerHTML='<h2>CÓMO JUGAR</h2><p>Elige un modo, compra skins y ventajas, supera niveles y alcanza un prestigio cada 10 niveles. Cada nuevo prestigio concede 1000 monedas. Arrastra el dedo cerca de la bola para moverla sin que se coloque directamente bajo tu pulsación. Recoge monedas, ventajas y meteoritos con multiplicadores aleatorios. Evita rocas, pinchos, satélites, minas, láseres, portales y cometas.</p>';openModal()}
$('#playBtn').onclick=start;$('#retryBtn').onclick=start;$('#homeBtn').onclick=()=>{state='menu';gameOver.classList.add('hidden');menu.classList.remove('hidden')};$('#rankingBtn').onclick=openRanking;$('#chatBtn').onclick=openChat;$('#skinsBtn').onclick=openSkins;$('#missionsBtn').onclick=openMissions;$('#modesBtn').onclick=openModes;$('#powersBtn').onclick=openPowers;$('#howBtn').onclick=openHow;$('#closeModal').onclick=closeModal;$('#pauseBtn').onclick=()=>{if(state==='play'){state='pause';modalContent.innerHTML='<h2>PAUSA</h2><button id="resume" class="btn primary">CONTINUAR</button><button id="quit" class="btn secondary">SALIR AL MENÚ</button>';openModal();$('#resume').onclick=()=>{state='play';closeModal()};$('#quit').onclick=()=>{state='menu';hud.classList.add('hidden');closeModal();menu.classList.remove('hidden')}}};
