create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 18),
  score integer not null default 0,
  level integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 18),
  message text not null check (char_length(message) between 1 and 140),
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;
alter table public.messages enable row level security;

create policy "scores readable" on public.scores for select using (true);
create policy "scores insertable" on public.scores for insert with check (true);
create policy "messages readable" on public.messages for select using (true);
create policy "messages insertable" on public.messages for insert with check (true);

alter publication supabase_realtime add table public.messages;
